package settings;

import java.io.File;
import java.util.ResourceBundle;
import java.util.regex.Pattern;

public class Settings {
    public static final int
            MENU_ITEM_EXIT = 15,
            MENU_ITEM_EXPORT_REPO = 14,
            MENU_ITEM_RESET_BRANCH_TO_COMMIT = 13,
            MENU_ITEM_CREATE_NEW_REPO = 12,
            MENU_ITEM_SHOW_ACTIVE_BRANCH_HISTORY = 11,
            MENU_ITEM_CHECK_OUT = 10,
            MENU_ITEM_DELETE_BRANCH = 9,
            MENU_ITEM_CREATE_NEW_BRANCH = 8,
            MENU_ITEM_SHOW_ALL_BRANCHES = 7,
            MENU_ITEM_COMMIT = 6,
            MENU_ITEM_SHOW_CURRENT_STATUS = 5,
            MENU_ITEM_SHOW_ALL_HISTORY = 4,
            MENU_ITEM_CHANGE_REPO = 3,
            MENU_ITEM_NAME_UPDATE = 2,
            MAGIT_UI_MIN_HEIGHT = 600,
            MAGIT_UI_MIN_WIDTH = 900,
            MAGIT_UI_INTRO_MIN_WIDTH = 600,
            MAGIT_UI_DIALOG_BOX_WIDTH = 250,
            MAGIT_UI_DIALOG_BOX_HEIGHT = 125,
            MAGIT_UI_INTRO_MIN_HEIGHT = 400,
            MAGIT_UI_SETTINGS_MIN_WIDTH = 600,
            MAGIT_UI_SETTINGS_MIN_HEIGHT = 250,
            SBA_ONE_CORRECT_LENGTH = 40,
            MAGIT_UI_SMART_POPUP_MAX_WIDTH = 600,
            MAGIT_UI_SMART_POPUP_MAX_HEIGHT = 250,
            MIN_COMMENT_SUBSTRING = 0,
            MAX_COMMENT_SUBSTRING = 30,
            MAX_SHA_ONE_TABLE_LENGTH = 20,
            MENU_ITEM_OPEN_RESOURCE = 1;
    public static int MENU_SIZE = MENU_ITEM_EXIT;
    public static final String
            THEME_BLACK = "black",
            THEME_WHITE = "white",
            LANG_ENG = "english",
            LANG_HEB = "hebrew",
            RESOURCE_FILE = "languages.lang",
            CANCEL_BTN_CLICKED_STRING = "cancel",
            JAVAFX_NEWLINE_TEXTAREA = "\n",
            FXML_SETTINGS_WINDOW = "/magit/resource/settings.fxml",
            FXML_APPLICATION = "/magit/resource/magit.fxml",
            FXML_SMART_POPUP_BOX = "/magit/resource/smart_popup.fxml",
            FXML_DIALOG_BOX = "/magit/resource/dialogBox.fxml",
            FXML_INTRO_WINDOW = "/magit/resource/magit_intro.fxml",
            FXML_BRANCH_MANAGER = "/magit/resource/branchManager.fxml",
            ROOT_SUB_FOLDERS = "ROOT_SUB_FOLDERS",
            XML_EXTENSION = "xml",
            XML_FILE_REQUEST_TYPE = "*." + XML_EXTENSION,
            DOT_XML = "." + XML_EXTENSION,
            ROOT_SUB_FILES = "ROOT_SUB_FILES",
            KEY_ALL_FOLDERS = "ALL_FOLDER",
            KEY_ALL_FILES = "ALL_FILES",
            KEY_COMMIT_BRANCH_LIST = "KEY_COMMIT_BRANCH_LIST",
            KEY_COMMIT_LIST = "KEY_COMMIT_LIST",
            KEY_COUNTER_COMMIT = "KEY_COUNTER_COMMIT",
            KEY_ALL_COMMITS = "KEY_ALL_COMMITS",
            KEY_COUNTER_FILES = "KEY_COUNTER_FILES",
            KEY_COUNTER_FOLDERS = "KEY_COUNTER_FOLDERS",
            KEY_ROOT_FOLDER_PATH = "KEY_ROOT_FOLDER_PATH",
            XML_LOAD_PACKAGE = "xml.basic",
            MAGIT_BRANCH_HEAD = "head",
            MAGIT_FOLDER = ".magit",
            COMMIT_MAP = "COMMIT_MAP",
            TEMP_FILE = "temp.magit",
            EMPTY_STRING = "",
            BASIC_SLASH = "/",
            SEPARATOR_PATTERN = Pattern.quote(File.separator),
            XML_ITEM_COMMIT_TYPE = "MagitCommit",
            SHOW_STATUS_SEPARATOR = "=================================",
            EMPTY_COMMIT = "null",
            DATE_FORMAT = "dd.MM.yyyy-HH:mm:ss:SSS",
            MAGIT_BRANCH_MASTER = "master",
            FILE_ENCODING = "UTF-8",
            FOLDER_FILE_EXTENSION = "magit",
            FOLDER_DELIMITER = ",",
            FILE_TYPE_IN_FOLDER_TABLE = "file",
            FOLDER_TYPE_IN_FOLDER_TABLE = "folder",
            XML_ITEM_FILE_TYPE = "blob",
            XML_ITEM_FOLDER_TYPE = "folder",
            FOLDER_TABLE_DELIMITER = ",",
            REPOSITORY_NAME = "repository.magit",
            OBJECT_FOLDER = "object",
            BRANCHES_FOLDER = "branches",
            TEMP_FOLDER_NAME = "temp.magit",
            TEMP_UNZIP_FOLDER = "unZipTemp";
    public static final ResourceBundle language = ResourceBundle.getBundle(RESOURCE_FILE);
}