package exceptions;

import languages.LangEN;

public enum eErrorCodesXML {
    NONE_ROOT_FOLDER(LangEN.NONE_ROOT_FOLDER),
    DUPLICATE_ROOT_FOLDER(LangEN.DUPLICATE_ROOT_FOLDER),
    NONE_XML_FILE(LangEN.NONE_XML_FILE_EXTINCTION),
    DUPLICATE_ID_NUMBER(LangEN.DUPLICATE_ID_NUMBER),
    FOLDER_POINT_TO_NONSEXIST_BLOB(LangEN.FOLDER_POINT_TO_NONSEXIST_BLOB),
    FOLDER_POINT_TO_SELF(LangEN.FOLDER_POINT_TO_SELF),
    WRONG_DATE_FORMAT(LangEN.WRONG_DATE_FORMAT),
    ITEM_WITH_UNKNOWN_TYPE(LangEN.ITEM_WITH_UNKNOWN_TYPE),
    FOLDER_POINT_TO_NONSEXIST_FOLDER(LangEN.FOLDER_POINT_TO_NONSEXIST_FOLDER),
    COMMIT_POINT_TO_BLOB(LangEN.COMMIT_POINT_TO_BLOB),
    COMMIT_POINT_TO_NONE_ROOT_FOLDER(LangEN.COMMIT_POINT_TO_NONE_ROOT_FOLDER),
    BRANCH_POINT_TO_NONSEXIST_COMMIT(LangEN.BRANCH_POINT_TO_NONSEXIST_COMMIT),
    HEAD_POINT_TO_NONSEXIST_BRANCH(LangEN.HEAD_POINT_TO_NONSEXIST_BRANCH);

    private String errorMessage;

    eErrorCodesXML(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }
}
