package com.magit.settings;

public class LangEN {
    public static final String
            FOLDER_PERMISSIONS = "please check folder permissions and try again.",
            FILE_EXIST_OR_PERMISSIONS = "please check if file exist or have the right permissions.",
            COMMIT_CREATED_SUCCESSFULLY = "Commit created successfully!",
            FILE_NOT_EXIST = "Sorry, but file is not exist",
            PLEASE_ENTER_YOUR_NAME = "Please enter your user name: ",
            NOTHING_TO_SHOW = "No data to show..",
            CANNOT_RECOVER_BRANCH = "Cannot recover active barnch from HEAD, magit folder is corrupted!",
            CHANGE_NAME_SUCCESSFULLY_TO = "Active user name changed successfully to %s",
            CREATE_NEW_REPOSITORY_FAILED_ALREADY_EXIST = "Creating new repository failed!",
            ERROR_PARSE_CURRENT_DATE = "Sorry, but somehow i got a weird error.. sorry but you will need to try again.",
            ERROR_CREATE_COMMIT_FILE = "Error while create commit file, please check folder permissions.",
            DATE_FORMAT = "dd.MM.yyyy - HH:mm:ss:SSS",
            BRANCH_ALREADY_EXIST = "This branch already exist!",
            MAGIT_FOLDER_ALREADY_EXIST = "It's seems that the path you give us already an magit repository, we cannot create new repository there!",
            READ_FROM_FILE_FAILED = String.format("Reading from file failed, %s", FILE_EXIST_OR_PERMISSIONS),
            OPEN_BRANCH_FILE_FAILED = "Sorry but we can't open current branch file, please reload magit.",
            CREATE_TEMP_FILE_FAILED = String.format("Creating temp file for folder failed %s", FOLDER_PERMISSIONS),
            MENU_OPTION_OPEN_RESOURCE = "Open an XML repository file",
            MENU_OPTION_NAME_UPDATE = "Change user name",
            MENU_OPTION_CHANGE_REPO = "Change active repository",
            MENU_OPTION_SHOW_ALL_HISTORY = "Show current commit history",
            MENU_OPTION_SHOW_CURRENT_STATUS = "Show status",
            MENU_OPTION_COMMIT = "Commit",
            MENU_OPTION_SHOW_ALL_BRANCHES = "Show all branches",
            MENU_OPTION_CREATE_NEW_BRANCH = "Create new branch",
            MENU_OPTION_DELETE_BRANCH = "Delete branch",
            MENU_OPTION_CHECK_OUT = "Check-out",
            MENU_OPTION_SHOW_ACTIVE_BRANCH_HISTORY = "Show all commits",
            MENU_OPTION_CREATE_NEW_REPO = "Create new repository",
            ERROR_LOAD_REPOSITORY = "Error while loading repository, maybe one of magit file was corrupted, we can't do nothing!",
            MENU_OPTION_EXIT = "Exit",
            MENU_CHOICE_WRONG = "You choose wrong number, please try again.",
            MENU_PLEASE_CHOOSE = "Please choose your command number: ",
            END_PROGRAM_MESSAGE = "Thank you for using M.A.GIT, hope to see you again.",
            MENU_CHOICE_NOT_NUMBER = "You entered invalid number, please try again.",
            ASK_FOR_PATH_FOR_REPO = "Please enter path for your new repository: ",
            ENTER_YOUR_COMMAND_NUMBER = "Please enter you command number: ",
            USER_ADMINISTRATOR = "Administrator",
            MAGIT_BRANCH_HEAD_NAME = "HEAD",
            SHOW_STATUS_NEW = "New files:",
            SHOW_STATUS_EDITED = "Edited files:",
            SHOW_STATUS_DELETED = "Deleted files:",
            ERROR_COMMIT_FAILED = "Commit failed, please try again.",
            COMMAND_FAILED = "Command executing failed, please try again.",
            SHOW_STATUS_SAPERATOR = "=================================",
            MAGIT_TOP_MASSAGE = "Magit Menu                    Current User: ",
            ERROR_REPOSITORY = "Repository Error: ",
            ENTER_COMMENT_FOR_COMMIT = "Please enter your comment for new commit:",
            TRY_AGAIN_OR_CHOOSE_OTHER_COMMAND = "Press 'y' or 'YES' to try again or any key to return to main MAIN_MENU",
            COMMAND_EXECUTED_SUCCESSFULLY = "The command executed successfully!",
            NEW_REPOSITORY_CREATED_SUCCESSFULLY = "The repository '%s' created successfully!",
            ERROR_CREATE_FILE_HEAD = String.format("Creating HEAD branch file failed! %s.", FOLDER_PERMISSIONS),
            CREATE_MAGIT_FOLDER_FAILED = String.format("Creating magit folder failed! %s.", FOLDER_PERMISSIONS),
            CREATE_ZIP_FILE_FAILED = String.format("Creating zip file failed! %s.", FILE_EXIST_OR_PERMISSIONS),
            OPEN_FILE_FAILED = String.format("Opening file failed! %s.", FILE_EXIST_OR_PERMISSIONS),
            INSERT_FILE_TO_ZIP_FAILED = "Insert data to zip file failed! please try again.",
            WRITE_TO_FILE_FAILED = String.format("Writing to file failed! %s.", FILE_EXIST_OR_PERMISSIONS),
            CLOSE_FILE_FAILED = "Closing file failed, I really don't know what happens, please try command again.",
            SCAN_FOLDER_FAILED = "We sorry, but we can't scan the folder you give us.\nPlease try again.";
}
